### ISSUE TITLE
ProgressBar won't update if using custom FXML 

### ISSUE THREAD

**Issue by matheso** [edvin/fxlauncher-custom-ui#2]
Hi Edvin, 
 
I've been struggling for a few days with this silly issue and need your help. Working example code attached. I'm trying to do 2 things:

1) Only show the stage when downloading updates (ie - skip the '`createLoader`' method if possible)
2) Use an FXML file for the updater's visuals, while still having the progress bar update like your demo code does.

I've successfully integrated the custom UI into the fxlauncher.jar and the UI properly displays upon 
 application startup and also downloads any updates appropriately. I'm using an FXML file which contains a ProgressBar, and using the FXML's parent StackPane as "root" instead of a VBox like in your example. I initialize the `ProgressBar `in the CustomLauncherUI class using the FXML ProgressBar.

But when the UI is displayed it will *not* visually update the progress bar, even though the progress is being printed to console - showing it is in fact updating. Why won't the progress bar update?

Thank you.
[loadscreen.fxml.txt](https://github.com/edvin/fxlauncher-custom-ui/files/1066048/loadscreen.fxml.txt)

[TestUpdatingUI.txt](https://github.com/edvin/fxlauncher-custom-ui/files/1066050/TestUpdatingUI.txt)
[CustomLauncherUI.txt](https://github.com/edvin/fxlauncher-custom-ui/files/1066051/CustomLauncherUI.txt)

**Comment by edvin** [comment]
Hi! With regards to your simulation code, the explanation as to why this isn't working is simple :) I'm referring to this code:

```java
Platform.runLater(() -> {
    for (int i = 0; i < 10; i++) {
        try {
            Thread.sleep(300);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        ui.updateProgress(i * 0.1);
    }
});
```

You call `Platform.runLater`, but the code actually blocks the UI thread while in a loop. The UI will be blocked for 3 seconds, and even though you call updateProgress, after every 300 millis, the UI cannot show the update before your function ends.

For that to work, you would have to run in a background thread and call `ui.updateProgress` on the ui thread instead.

It would look something like this:

```java
new Thread(() -> {
    for (int i = 0; i < 10; i++) {
        try {
            Thread.sleep(300);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        final double progress = i * 0.1;
        Platform.runLater(() -> ui.updateProgress(progress));
        
    }
}).start();
```

An even better alternative would be to use a `javafx.concurrent.Task`, but it doesn't matter for this test code I suppose.

When you have confirmed that the progress bar is updating correctly you can continue with the integration :) Let me know if you run into more trouble :)

**Comment by matheso** [comment]
Thanks for that, I tried your solution and also tried putting the loop within a full Task, in both the Test class and the CustomLauncherUI class and it still won't update the bar. The same result occurs when I deploy my app and run the jar or native installer after, it shows the UI but the progress won't increase (yet the increasing progress value is being printed to console). The UI properly closes once downloads have finished but the progress bar never changes.

So it doesn't look like just an issue with the simulation code, any ideas? Thank you kindly :)

**Comment by edvin** [comment]
That seems to be because you create a new scene inside `createUpdater` and assign that scene to the stage. Remove these three lines and it should work:

```java
Scene scene = new Scene(root, 673, 268);
scene.setFill(Color.TRANSPARENT);
stage.setScene(scene);
```

I guess you did this because of your first requirement. I haven't looked into the possibility of not showing the stage for createLoader yet :)

**Comment by edvin** [comment]
I found a way to not show the loader. It consists of the following steps:

1. Create a stylesheet that has the following definition:

```css
.root { -fx-background-color: transparent; }
```

2. Load that CSS, set the stage style to `StageStyle.TRANSPARENT`, the scene fill to `Color.TRANSPARENT` and return a simple parent, like a `Pane` as the UI for the `createLoader` method:

```java
public Parent createLoader() {
    stage.getScene().getStylesheets().add(getClass().getResource("/transparent.css").toExternalForm());
    stage.initStyle(StageStyle.TRANSPARENT);
    stage.getScene().setFill(Color.TRANSPARENT);
    return new Pane();
}
```
You might want to unload or override that stylesheet in your `createUpdater` method :)

**Comment by matheso** [comment]
The progress bar seems fixed :) The scene was the culprit! Thanks so much. I'm starting to understand FXLauncher more deeply and am amazed by your creation. Seriously.

I'll test out your loader hiding solution when I return home tonight, but I'm sure it'll work. Thank you sir :)

**Comment by matheso** [comment]
Everything works great, appreciate your help Edvin. Take care.

**Comment by edvin** [comment]
I'm glad to hear it :) FXLauncher isn't very impressive internally, and I have several ideas for a reboot of it. Right now I'm waiting to see what becomes of Kotlin Native for Windows before I decide how the reboot will look like. I would like to have the ability to update the JVM as well, amongst several other nice features :)
