### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: org/springframework/context/ConfigurableApplicationContext

### ISSUE THREAD

**Issue by Alphalatot** [edvin/fxlauncher-custom-ui#6]
Hello

I am integrating spring boot with javafx and added fxlauncher, which is very good and working propery, however when adding custom ui for fxlauncher I encounter this problem.

**here are the error messages:**

`WARNING: Failed to start application
java.lang.NoClassDefFoundError: org/springframework/context/ConfigurableApplicationContext
        at com.alphalatot.springfx.JavafxApplication.start(JavafxApplication.java:34)
        at fxlauncher.Launcher.startApplication(Launcher.java:242)
        at fxlauncher.Launcher.lambda$launchAppFromManifest$2(Launcher.java:194)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method)
        at com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:204)
        at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511)
        at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107)
        at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:590)
        at javafx.stage.Stage.showAndWait(Stage.java:474)
        at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
        at javafx.scene.control.Dialog.showAndWait(Dialog.java:341)
        at fxlauncher.Launcher$1.lambda$reportError$2(Launcher.java:84)
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$3(WinApplication.java:177)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.springframework.context.ConfigurableApplicationContext
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 24 more
`
**here is my pom.xml**

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.1.RELEASE</version>
		<relativePath/> 
	</parent>
	<groupId>com.alphalatot</groupId>
	<artifactId>springfx</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>springfx</name>
	<description>Integrating spring with javafx</description>

	<properties>
		<java.version>1.8</java.version>
		
		<app.filename>SpringFx</app.filename>

		
		<app.mainClass>com.alphalatot.springfx.JavafxApplication</app.mainClass>

		
		<app.cacheDir>USERLIB/springfx</app.cacheDir>

		
		<app.parameters></app.parameters>

		
		<app.vendor>SpringFx Inc.</app.vendor>

		
		<app.version>${project.version}</app.version>

		
		<app.url>http://127.0.0.1/springfx</app.url>

		
		<app.deploy.target></app.deploy.target>

		
		<app.dir>${project.build.directory}/app</app.dir>

		
		<app.installerdir>${project.build.directory}/installer</app.installerdir>

		
		<app.acceptDowngrade>false</app.acceptDowngrade>

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.10</version>
		</dependency>
		<dependency>
			<groupId>com.jfoenix</groupId>
			<artifactId>jfoenix</artifactId>
			<version>8.0.9</version>
		</dependency>
		<dependency>
			<groupId>no.tornado</groupId>
			<artifactId>fxlauncher</artifactId>
			<version>1.0.21</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<build>
		
		<plugins>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.6</version>
				<configuration>
					<outputDirectory>${app.dir}</outputDirectory>
				</configuration>
			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<configuration>
					<excludeScope>provided</excludeScope>
					<outputDirectory>${app.dir}</outputDirectory>
					<stripVersion>true</stripVersion>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.4.0</version>
				
				<executions>
					<execution>
						<id>create-manifest</id>
						<phase>package</phase>
						<goals>
							<goal>java</goal>
						</goals>
						<configuration>
							<mainClass>fxlauncher.CreateManifest</mainClass>
							<arguments>
								<argument>${app.url}</argument>
								<argument>${app.mainClass}</argument>
								<argument>${app.dir}</argument>
								<argument>--cache-dir=${app.cacheDir}</argument>
								<argument>--accept-downgrade=${app.acceptDowngrade}</argument>
								<argument>--include-extensions=jpg</argument>
								<argument>${app.parameters}</argument>
							</arguments>
						</configuration>
					</execution>
					
					<execution>
						<id>embed-manifest-in-launcher</id>
						<phase>package</phase>
						<goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<executable>jar</executable>
							<workingDirectory>${app.dir}</workingDirectory>
							<arguments>
								<argument>uf</argument>
								<argument>fxlauncher.jar</argument>
								<argument>app.xml</argument>
							</arguments>
						</configuration>
					</execution>
					
					<execution>
					<id>embed-custom-ui-in-launcher</id>
                        <phase>package</phase>
                        <goals>
                        	<goal>exec</goal>
                        </goals>
                        <configuration>
							<executable>jar</executable>
							<workingDirectory>${app.dir}</workingDirectory>
							<arguments>
								<argument>uf</argument>
								<argument>fxlauncher.jar</argument>
								<argument>-C</argument>
								<argument>${project.basedir}/../Bravo/target/classes</argument>
								<argument>.</argument>
							</arguments>
                        </configuration>
					</execution>
					
					<execution>
						<id>installer</id>
						<phase>install</phase>
						<goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<executable>javapackager</executable>

							<arguments>
								<argument>-deploy</argument>
								<argument>-native</argument>
								<argument>-outdir</argument>
								<argument>${app.installerdir}</argument>
								<argument>-outfile</argument>
								<argument>${app.filename}</argument>
								<argument>-srcdir</argument>
								<argument>${app.dir}</argument>
								<argument>-srcfiles</argument>
								<argument>fxlauncher.jar</argument>
								<argument>-appclass</argument>
								<argument>fxlauncher.Launcher</argument>
								<argument>-name</argument>
								<argument>${project.name}</argument>
								<argument>-title</argument>
								<argument>${project.name}</argument>
								<argument>-vendor</argument>
								<argument>${app.vendor}</argument>
								<argument>-BappVersion=${app.version}</argument>
								<argument>-Bidentifier=${project.groupId}.${project.artifactId}</argument>
								<argument>-BjvmOptions=-XX:+UseG1GC</argument>
							</arguments>
						</configuration>
					</execution>
					
					<execution>
						<id>deploy-app</id>
						<goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<executable>scp</executable>
							<arguments>
								<argument>-r</argument>
								<argument>target/app/.</argument>
								<argument>${app.deploy.target}</argument>
							</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*.fxml</include>
					<include>**/*.css</include>
				</includes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>**/*.properties</include>
					<include>**/*.css</include>
					<include>**/*.UIProvider</include>
				</includes>
			</resource>
		</resources>
	</build>

</project>
`

**Here is my JavaFxApplication**

`package com.alphalatot.springfx;

import com.alphalatot.springfx.services.GuiService;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;

@SpringBootApplication
public class JavafxApplication extends Application {

    private ConfigurableApplicationContext applicationContext;
    private String SOURCE_ROOT;
    private String RESOURCE_ROOT;

    public static void main(String[] args) {
        launch(JavafxApplication.class, args);
    }

    @Override
    public void init() throws Exception {
        this.applicationContext = new SpringApplicationBuilder(JavafxApplication.class).headless(false).run();
    }

    @Override
    public void start(Stage stage) throws Exception {
        this.SOURCE_ROOT = getClass().getResource("").toExternalForm();
        this.RESOURCE_ROOT = getClass().getResource("").toExternalForm();
        System.out.println(SOURCE_ROOT);
        System.out.println(RESOURCE_ROOT);
        GuiService guiService = this.applicationContext.getBean(GuiService.class);
        guiService.setSOURCE_ROOT(this.SOURCE_ROOT);
        stage.setScene(new Scene(guiService.load(SOURCE_ROOT + "components/dashboard/dashboard.fxml")));
        stage.show();
        System.gc();
    }

    @Override
    public void stop() throws Exception {
        this.applicationContext.close();
        Platform.exit();
    }
}
`

**Comment by edvin** [comment]
You need to either embed the Spring Boot resources into the launcher, or refrain from using Spring Boot in the custom launcher code :)

**Comment by Alphalatot** [comment]
Thanks ! it is working now after pulling an all nighter. The problem is i did not read properly and miss this part "It is recommended that you create a separate project for the custom UI to make it easier to embed it into the fxlauncher.jar", Great project btw.

**Comment by edvin** [comment]
Thanks for reporting back :)
